### PR TITLE
Add repo instructions option

### PR DESCRIPTION
**Pull request by ryx2**
This way, users can pass in their own files for additional instructions in the .jinja:

```
{% if repo_instruction %}

Some basic information about this repository:
{{ repo_instruction }}{% endif %}
```

### CODE REVIEW

**Comment by ryx2** [comment]
@neubig I am running this openhands-resolver code on multiple of my repos, so I would appreciate the option to switch instructions and keep those instructions in the repo that's being edited itself, as opposed to needing to make a branch on my fork of this openhands-resolver repo that contains an edit of the `.openhands_instructions` file

**Comment by neubig** [comment]
Hey @ryx2 , yes, you can already do that. Add `.openhands_instructions` file to the top directory any repo that you're working on and it will automatically be pulled in by the resolver without any code changes.

**Comment by neubig** [comment]
Here's an example: https://github.com/All-Hands-AI/OpenHands/blob/main/.openhands_instructions

**Comment by ryx2** [comment]
ok! is it possible to throw a line into the readme.md so people like me would be able to understand the .openhands_instructions goes into the prompt? I can also add that line in a separate PR if you let me know what section it would be best in

**Comment by neubig** [comment]
Hey @ryx2 , yes a PR for the readme would be awesome! I think a new section "providing custom instructions" would be good. We could maybe add a few examples like the one from this repo and the one from the openhands repo.

**Comment by malhotra5** [comment]
+1 on this; I think maybe the section should be called "advanced settings" or "custom settings"? This would include a guide  for setting repo instructions as detailed above + a custom macro to invoke `openhands-resolver` (introduced in #323)?

**Comment by ryx2** [comment]
@malhotra5 I don't know what the custom macro is, but i just made a PR for just the `.openhands_instructions`, maybe you could add on the macro to that same section after a merge?

**Pull request closed without merging**
