### PR TITLE
Update openhands-ai to 0.12.0

### PR DESCRIPTION
**Pull request by neubig**
This PR updates openhands-ai to version 0.12.0 and fixes the runtime import path.

Changes:
- Update openhands-ai dependency to ^0.12.0
- Fix runtime import from `openhands.runtime.runtime` to `openhands.runtime.base`
- Update poetry.lock file

All tests are passing.

Fixes https://github.com/All-Hands-AI/openhands-resolver/pull/218

### CODE REVIEW

**Comment by neubig** [comment]
Thanks @malhotra5 , I conveyed this to OpenHands :)

**Comment by malhotra5** [comment]
> I believe `await runtime.connect()` also needs to be added after `initialize_runtime(runtime)`
> 
> this is around line 246 in `openhands_resolver/resolve_issues.py`

apologies there is a correction, `await runtime.connect()`  needs to be added BEFORE `initialize_runtime(runtime)`

**Comment by neubig** [comment]
Hey @malhotra5 , hmm, I tried debugging this now and am having issues running it locally. I ran out of time, but if you have a minute it'd be great if you could take a look!

**Comment by neubig** [comment]
Awesome, thanks @xingyaoww . @malhotra5 please disregard.

**Pull request merged**
